### ISSUE TITLE
«undefined method `before_filter' for CategoriesController:Class»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [discourse-pro/df-core-private#3]
![02](https://user-images.githubusercontent.com/83204/34747582-0c263f82-f5c3-11e7-807b-ed17a90e37d6.png)

```
rake aborted!
NoMethodError: undefined method `before_filter' for CategoriesController:Class
Did you mean?  before_action
plugins/df-core-private/plugin.rb:18:in `block (2 levels) in activate!'
plugins/df-core-private/plugin.rb:17:in `class_eval'
plugins/df-core-private/plugin.rb:17:in `block in activate!'
lib/plugin/instance.rb:254:in `block in notify_after_initialize'
lib/plugin/instance.rb:252:in `each'
lib/plugin/instance.rb:252:in `notify_after_initialize'
config/application.rb:211:in `each'
config/application.rb:211:in `block in <class:Application>'
config/environment.rb:5:in `<main>'
~/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
~/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>'
```

**Comment by dmitrii-fediuk** [comment]
Fixed in [1.1.1](https://github.com/discourse-pro/df-core-private/releases/tag/1.1.1).
